version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hello_visitor
      - DB_USERNAME=root
      - DB_PASSWORD=your_password
      - APACHE_RUN_USER=www
    depends_on:
      - db
    ports:
      - "8013:80"

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: hello_visitor
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
